apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-static-site
  labels:
    app: my-static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-static-site
  template:
    metadata:
      labels:
        app: my-static-site
    spec:
      containers:
      - name: my-static-site
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
