apiVersion: v1
kind: Service
metadata:
  name: my-static-site
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-static-site
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
